name: Java CI Build und Test

# Nur ausf체hren, wenn in den main-Branch gepusht wird
on: 
  push:
    branches: [ main ]

jobs:
  build_und_test:
    # Der Job l채uft auf der neuesten Ubuntu-Version
    runs-on: ubuntu-latest

    # Die Schritte, die in diesem Job ausgef체hrt werden
    steps:

    # Code aus dem Repository holen
    - name: Checkout repository
      uses: actions/checkout@v4

    # Java JDK 25 einrichten
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'

    - name: Java-Projekt kompilieren
      run: javac -d bin src/*.java

    - name: Java-Tests ausf체hren
      run: java --class-path bin Main
