name: Java CI Build und Test für Woche 3 Aufgabe 3

# Nur ausführen, wenn in den main-Branch gepusht wird
on: push
  #push:
  #  paths:
  #  - 'SWE/lekrieger-dwerwein_03/Aufgabe_3/**'
  #  branches: [ main ]

jobs:
  build_und_test:
    # Der Job läuft auf der neuesten Ubuntu-Version
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'SWE/lekrieger-dwerwein_03/Aufgabe_3'

    # Die 4 Schritte, die in diesem Job ausgeführt werden
    steps:
    #1 
    - name: Repository auschecken
      uses: actions/checkout@v4
    #2
    - name: JDK 25 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
    #3
    - name: Java-Projekt kompilieren
      run: javac -d bin src/*.java
    #4
    - name: Java-Tests ausführen
      run: java --class-path bin Main
